import './tokens.scss';
import './internal/field-shell.scss';
import './foundation/button.scss';
import './foundation/icon.scss';
import './foundation/link.scss';
import './foundation/loader.scss';
import './form/input-field.scss';
import './form/textarea.scss';
import './form/check-control.scss';
import './form/select.scss';
import './form/search-select.scss';
import './form/inheritance-control.scss';
import './form/native-picker.scss';
import './layout/card.scss';
import './layout/space.scss';
import './feedback/banner.scss';
import './feedback/badge.scss';
import './feedback/progress.scss';
import './feedback/skeleton.scss';
import './feedback/empty-state.scss';
import './navigation/tabs.scss';
import './navigation/pagination.scss';
import './overlay/modal.scss';
import './overlay/tooltip.scss';
import './overlay/popover.scss';
import './overlay/action-menu.scss';
import './data/data-table.scss';
import './data/entity-table.scss';
import './data/rich-text-editor.scss';
import './data/chart.scss';
import './media/avatar.scss';
import './media/media-preview.scss';
import './media/media-upload.scss';

import './form/input-fields';
import './form/check-controls';
import './form/search-selects';
import './form/native-pickers';
import './layout/spaces';
import './overlay/action-menus';

Shopware.Component.register('jetpack-field-shell', () => import('./internal/field-shell'));
Shopware.Component.register('jetpack-button', () => import('./foundation/button'));
Shopware.Component.register('jetpack-icon', () => import('./foundation/icon'));
Shopware.Component.register('jetpack-link', () => import('./foundation/link'));
Shopware.Component.register('jetpack-loader', () => import('./foundation/loader'));
Shopware.Component.register('jetpack-textarea', () => import('./form/textarea'));
Shopware.Component.register('jetpack-select', () => import('./form/select'));
Shopware.Component.register('jetpack-entity-select', () => import('./form/entity-select'));
Shopware.Component.register('jetpack-entity-multi-select', () => import('./form/entity-multi-select'));
Shopware.Component.register('jetpack-inheritance-control', () => import('./form/inheritance-control'));
Shopware.Component.register('jetpack-card', () => import('./layout/card'));
Shopware.Component.register('jetpack-tabs', () => import('./navigation/tabs'));
Shopware.Component.register('jetpack-empty-state', () => import('./feedback/empty-state'));
Shopware.Component.register('jetpack-banner', () => import('./feedback/banner'));
Shopware.Component.register('jetpack-badge', () => import('./feedback/badge'));
Shopware.Component.register('jetpack-progress', () => import('./feedback/progress'));
Shopware.Component.register('jetpack-skeleton', () => import('./feedback/skeleton'));
Shopware.Component.register('jetpack-pagination', () => import('./navigation/pagination'));
Shopware.Component.register('jetpack-modal', () => import('./overlay/modal'));
Shopware.Component.register('jetpack-tooltip', () => import('./overlay/tooltip'));
Shopware.Component.register('jetpack-popover', () => import('./overlay/popover'));
Shopware.Component.register('jetpack-data-table', () => import('./data/data-table'));
Shopware.Component.register('jetpack-entity-table', () => import('./data/entity-table'));
Shopware.Component.register('jetpack-rich-text-editor', () => import('./data/rich-text-editor'));
Shopware.Component.register('jetpack-chart', () => import('./data/chart'));
Shopware.Component.register('jetpack-avatar', () => import('./media/avatar'));
Shopware.Component.register('jetpack-media-preview', () => import('./media/media-preview'));
Shopware.Component.register('jetpack-media-upload', () => import('./media/media-upload'));
